export const REQUEST_SPELLS_REFERENCE = 'REQUEST_SPELLS_REFERENCE'
export const INVALIDATE_SPELLS_REFERENCE = 'INVALIDATE_SPELLS_REFERENCE'
export const RECEIVE_SPELLS_REFERENCE = 'RECEIVE_SPELLS_REFERENCE'